<a href="https://colab.research.google.com/github/linqus/nlp-huggingface/blob/main/notebooks/unit2/nlp_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.0 MB/s eta 0:00:00


In [20]:
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification

In [23]:
sequences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I like icecreams too"
]
prompt ="I've been waiting for a HuggingFace course my whole life."
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokens = tokenizer.tokenize(sequences)
print("raw tokens: ",tokens)
output = tokenizer.convert_tokens_to_ids(tokens)
print("converted ids: ", ids)

tensor = torch.tensor(ids)
print("tensor without dim: ", tensor)

tensor_dim = torch.tensor([ids])
print("tensor with dimention: ", tensor_dim)

model_input = tokenizer(prompt, return_tensors="pt")
print("from tokenizer: ", model_input['input_ids'])

model = AutoModel.from_pretrained(checkpoint)
output = model(tensor_dim)
print("output from tensor with dim: ", output)

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
output = model(tensor_dim)
print("classificator logit output: ", output["logits"])


batched_ids = [ids, ids]
tensor_batched = torch.tensor(batched_ids)
output = model(tensor_batched)
print("classificator logit output (batched): ", output["logits"])

raw tokens:  ['i', "'", 've', 'been', 'waiting', 'for', 'a', 'hugging', '##face', 'course', 'my', 'whole', 'life', '.', 'i', 'like', 'ice', '##cre', '##ams', 'too']
converted ids:  [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 1045, 2066, 3256, 16748, 13596, 2205]
tensor without dim:  tensor([ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
         2026,  2878,  2166,  1012,  1045,  2066,  3256, 16748, 13596,  2205])
tensor with dimention:  tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012,  1045,  2066,  3256, 16748, 13596,  2205]])
from tokenizer:  tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102]])
output from tensor with dim:  BaseModelOutput(last_hidden_state=tensor([[[-0.4245,  0.4682,  0.4638,  ..., -0.0660,  0.0738, -0.0355],
         [-0.1034,  0.6148,  0.6247,  ..., -0.14

In [40]:
sequence1 = [[200, 200, 200]]
sequence2 = [[200, 200]]

batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id]
]
tensor1 = torch.tensor(sequence1)
print(tensor1)

tensor2 = torch.tensor(sequence2)
print(tensor2)

batched_tensor = torch.tensor(batched_ids)
print(batched_tensor)


print(model(tensor1).logits)
print(model(tensor2).logits)
print(model(batched_tensor).logits)

tensor([[200, 200, 200]])
tensor([[200, 200]])
tensor([[200, 200, 200],
        [200, 200,   0]])
tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [42]:
attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

attention_tensor = torch.tensor(attention_mask)

print(model(batched_tensor, attention_mask=attention_tensor).logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
