<a href="https://colab.research.google.com/github/linqus/nlp-huggingface/blob/main/notebooks/unit2/nlp_2_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 14.8 MB/s eta 0:00:00


In [3]:
from transformers import AutoTokenizer

In [8]:
prompt = "I've been waiting for a HuggingFace course my whole life."

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenized = tokenizer(prompt)
print(tokenized)

sequences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "So have I!",
]

tokenized = tokenizer(sequences)
print("batched: ", tokenized)


tokenized = tokenizer(sequences, padding="longest")
print("batched padding-longest: ", tokenized)

tokenized = tokenizer(sequences, padding="max_length")
print("batched padding-max: ", tokenized)

tokenized = tokenizer(sequences, padding="max_length", max_length=8)
print("batched padding-max(8): ", tokenized)


tokenized = tokenizer(sequences, padding="max_length", max_length=8, truncation=True)
print("batched padding-max(8) trunc: ", tokenized)

{'input_ids': [101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
batched:  {'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 2061, 2031, 1045, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}
batched padding-longest:  {'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 2061, 2031, 1045, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}
batched padding-max:  {'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [11]:
tensor_pt = tokenizer(sequences, return_tensors="pt", padding=True)
print(tensor_pt)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  2061,  2031,  1045,   999,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [13]:
tensor_tf = tokenizer(sequences, return_tensors="tf", padding=True)
print(tensor_tf)

{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  2061,  2031,  1045,   999,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>}


In [14]:
tensor_np = tokenizer(sequences, return_tensors="np", padding=True)
print(tensor_np)

{'input_ids': array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  2061,  2031,  1045,   999,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [35]:
print(prompt)
print("--")

tokens = tokenizer.tokenize(prompt)
ids = tokenizer.convert_tokens_to_ids(tokens)
print("raw ids :", ids)

decoded_ids = tokenizer.decode(ids)
print("decoded raw ids: ", decoded_ids)

print("--")
special_ids = tokenizer(prompt)['input_ids']
print("ids with spectokens: ", special_ids)

decoded_tok = tokenizer.decode(special_ids)
print("decoded with spectokens: ", decoded_tok)



I've been waiting for a HuggingFace course my whole life.
--
raw ids : [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
decoded raw ids:  i've been waiting for a huggingface course my whole life.
--
ids with spectokens:  [101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102]
decoded with spectokens:  [CLS] i've been waiting for a huggingface course my whole life. [SEP]


In [52]:
print(sequences)
print("--")

tokens = tokenizer.tokenize(sequences)
ids = tokenizer.convert_tokens_to_ids(tokens)
print("raw ids :", ids)

decoded_ids = tokenizer.batch_decode([ids])
print("decoded raw ids: ", decoded_ids)

print("--")
special_ids = tokenizer(sequences)
print("ids with spectokens: ", special_ids)

decoded_tok = tokenizer.batch_decode(special_ids['input_ids'])
print("decoded with spectokens: ", decoded_tok)

["I've been waiting for a HuggingFace course my whole life.", 'So have I!']
--
raw ids : [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 2061, 2031, 1045, 999]
decoded raw ids:  ["i've been waiting for a huggingface course my whole life. so have i!"]
--
ids with spectokens:  {'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 2061, 2031, 1045, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}
decoded with spectokens:  ["[CLS] i've been waiting for a huggingface course my whole life. [SEP]", '[CLS] so have i! [SEP]']


In [57]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

special_ids_padded = tokenizer(sequences, padding=True, return_tensors="pt")
print(special_ids_padded)
print(model(**special_ids_padded))

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  2061,  2031,  1045,   999,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}
SequenceClassifierOutput(loss=None, logits=tensor([[-1.5607,  1.6123],
        [-3.6183,  3.9137]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
